# Generated by Django 4.1.3 on 2022-11-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kategori', models.CharField(max_length=100)),
                ('des_kategori', models.TextField()),
                ('img_kategori', models.ImageField(null=True, upload_to='gambarkt/')),
            ],
        ),
        migrations.CreateModel(
            name='Mainscreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_mainscreen', models.CharField(max_length=100)),
                ('des_mainscreen', models.TextField()),
                ('img_mainscreen', models.ImageField(null=True, upload_to='gambarms/')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_province', models.CharField(max_length=100)),
                ('des_bahasa', models.TextField()),
                ('img_bahasa', models.ImageField(null=True, upload_to='gambar/')),
                ('des_agama', models.TextField()),
                ('img_agama', models.ImageField(null=True, upload_to='gambar/')),
                ('des_kesenian', models.TextField()),
                ('img_kesenian', models.ImageField(null=True, upload_to='gambar/')),
                ('des_khas', models.TextField()),
                ('img_khas', models.ImageField(null=True, upload_to='gambar/')),
                ('des_pakaian', models.TextField()),
                ('img_pakaian', models.ImageField(null=True, upload_to='gambar/')),
                ('des_alatmusik', models.TextField()),
                ('img_alatmusik', models.ImageField(null=True, upload_to='gambar/')),
                ('des_pesan', models.TextField()),
            ],
        ),
    ]
