# Generated by Django 4.1.3 on 2022-11-19 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=100)),
                ('des_category', models.TextField()),
                ('img_category', models.ImageField(null=True, upload_to='gambar/')),
            ],
        ),
        migrations.DeleteModel(
            name='Kategori',
        ),
        migrations.DeleteModel(
            name='Mainscreen',
        ),
        migrations.RenameField(
            model_name='province',
            old_name='des_agama',
            new_name='pesan',
        ),
        migrations.RemoveField(
            model_name='province',
            name='des_alatmusik',
        ),
        migrations.RemoveField(
            model_name='province',
            name='des_bahasa',
        ),
        migrations.RemoveField(
            model_name='province',
            name='des_kesenian',
        ),
        migrations.RemoveField(
            model_name='province',
            name='des_khas',
        ),
        migrations.RemoveField(
            model_name='province',
            name='des_pakaian',
        ),
        migrations.RemoveField(
            model_name='province',
            name='des_pesan',
        ),
        migrations.RemoveField(
            model_name='province',
            name='img_agama',
        ),
        migrations.RemoveField(
            model_name='province',
            name='img_alatmusik',
        ),
        migrations.RemoveField(
            model_name='province',
            name='img_bahasa',
        ),
        migrations.RemoveField(
            model_name='province',
            name='img_kesenian',
        ),
        migrations.RemoveField(
            model_name='province',
            name='img_khas',
        ),
        migrations.RemoveField(
            model_name='province',
            name='img_pakaian',
        ),
        migrations.AddField(
            model_name='province',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.category'),
        ),
    ]
