# Generated by Django 4.0.6 on 2022-11-19 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_province_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.category'),
        ),
    ]
