# Generated by Django 4.0.6 on 2022-11-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_province_category_category_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisekitarAnda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_disekitar', models.CharField(max_length=100)),
                ('des_disekitar', models.TextField()),
                ('date_disekitar', models.DateField()),
                ('img_disekitar', models.ImageField(blank=True, null=True, upload_to='gambar/')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='img_category',
            field=models.ImageField(blank=True, null=True, upload_to='gambar/'),
        ),
    ]
