# Generated by Django 4.0.6 on 2022-11-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_disekitaranda_alter_category_img_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeritaKebudayaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_berita', models.CharField(max_length=100)),
                ('des_berita', models.TextField()),
                ('date_berita', models.DateField()),
                ('img_berita', models.ImageField(blank=True, null=True, upload_to='gambar/')),
            ],
        ),
        migrations.CreateModel(
            name='EventMendatang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_event', models.CharField(max_length=100)),
                ('des_event', models.TextField()),
                ('date_event', models.DateField()),
                ('img_event', models.ImageField(blank=True, null=True, upload_to='gambar/')),
            ],
        ),
    ]
