# Generated by Django 4.0.6 on 2022-11-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_beritakebudayaan_eventmendatang'),
    ]

    operations = [
        migrations.AddField(
            model_name='beritakebudayaan',
            name='judul_berita',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='disekitaranda',
            name='judul_disekitar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventmendatang',
            name='judul_event',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
