# Generated by Django 4.1.3 on 2022-11-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_beritakebudayaan_judul_berita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='img_province',
            field=models.ImageField(blank=True, null=True, upload_to='gambar/'),
        ),
    ]
