# Generated by Django 4.1.3 on 2022-11-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_province_img_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('img_budaya', models.ImageField(blank=True, null=True, upload_to='gambar/')),
            ],
        ),
    ]
