# Generated by Django 4.1.3 on 2022-11-23 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_isibudaya'),
    ]

    operations = [
        migrations.AddField(
            model_name='budaya',
            name='isibudaya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.isibudaya'),
        ),
    ]
