# Generated by Django 4.1.3 on 2022-11-23 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_isibudaya_province'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budaya',
        ),
    ]
