# Generated by Django 4.1.3 on 2022-11-23 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_delete_budaya'),
    ]

    operations = [
        migrations.AddField(
            model_name='isibudaya',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.category'),
        ),
    ]
