# Generated by Django 4.1.3 on 2022-11-24 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_isibudaya_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='pesan',
        ),
    ]
