# Generated by Django 4.1.3 on 2022-11-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_remove_province_pesan'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='slug',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
